services:
 api:
   build:
     context: .
   env_file:
     - .env
   ports:
     - "8000:8000"
   command: >
      sh -c "python db/wait_db.py &&
            python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000
            "
   volumes:
     - /Users/kostyantynzivenko/Desktop/my_experiments/UCC/library_backend:/app
   depends_on:
     - db

 db:
   image: postgres:16-alpine3.19
   restart: always
   env_file:
     - .env
   ports:
     - "${POSTGRES_PORT}:5432"
   volumes:
     - my_db:${PGDATA}

volumes:
  my_db: