# Generated by Django 5.0.1 on 2024-02-19 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=63)),
                ("last_name", models.CharField(max_length=63)),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=31, unique=True)),
            ],
            options={
                "db_table_comment": "Describes a literary genre, such as: a novel, a detective story, a children's tale, fantasy, etc.",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=31, unique=True)),
            ],
            options={
                "db_table_comment": "Tags that users can create and add.",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=31, unique=True)),
            ],
            options={
                "db_table_comment": "Describes the type of object, such as: book, magazine, board game, etc.",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("isbn", models.CharField(blank=True, max_length=13, null=True)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("EX", "Excellent."),
                            ("GOOD", "Good."),
                            ("S", "Satisfactory."),
                            ("NR", "Needs repair."),
                            ("REPL", "Needs replacement."),
                            ("D", "Disassembled: missing some elements."),
                        ],
                        default="EX",
                        max_length=4,
                        verbose_name="Condition",
                    ),
                ),
                (
                    "cost_of_compensation",
                    models.DecimalField(
                        decimal_places=2, default=10.0, max_digits=6, null=True
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.genre",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.type"
                    ),
                ),
            ],
        ),
    ]
