name: Lint&test

on:
  - push
  - pull_request

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: flake8 Lint
        uses: py-actions/flake8@v2

  black:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: psf/black@stable
          with:
            options: "--check --verbose"

  doctest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
